language: java
sudo: false
os:
- linux
dist: trusty
jdk:
- openjdk11
cache:
    directories:
    - "$HOME/.m2"

install:
script:
- ./mvnw package -B

deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
      branch: "master"
