spring:
    profiles:
        include:
        - secret-local
    datasource:
        url: jdbc:mysql://localhost:3306/market-dev?useSSL=false
        username: root
        password: 123456
    jpa:
        show-sql: true
    security:
        user:
            name: user
            password: 123456
jwt:
    secret: scutsu-market-develop-jwt-secret

upload:
    local:
        directory: ./upload/

# uncomment the following lines to let hibernate generate database tables
#spring.jpa.hibernate.ddl-auto: create
#spring.liquibase.enabled: false
