spring:
    profiles:
        active: development
    jpa:
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
        open-in-view: false
we-chat:
    template-message:
        templates:
            review-approved:
                template-id: CfgbsJLtz2nn9NPj0KSDY2gpJwyaVz8SHp8xRPY6tbs
                keywords:
                    title: keyword1
                    remark: keyword2
                    submitted-time: keyword3
                    reviewed-time: keyword4
            review-change-requested:
                template-id: K-6DRvZwVZxNmJE9MsBBp5gZDQXckPTFv8y3oH5felM
                keywords:
                    title: keyword1
                    comments: keyword2
                    remark: keyword3
                    submitted-time: keyword4
                    reviewed-time: keyword5
