spring:
    datasource:
        url: jdbc:mysql://localhost:3306/market-dev?useSSL=false
        username: root
        password: 123456
    jpa:
        show-sql: true

# uncomment the following lines to let hibernate generate database tables
#spring.jpa.hibernate.ddl-auto: create
#spring.liquibase.enabled: false
